### ISSUE TITLE
Can't access memory

### ISSUE THREAD

**Issue by serfend** [danigargu/heap-viewer#20]
```python
Traceback (most recent call last):
  File "~/plugins\heap_viewer\plugin_gui.py", line 141, in reload_gui_info
    self.arena_widget.populate_table()
  File "~/plugins\heap_viewer\widgets\arena.py", line 131, in populate_table
    parsed_heap = self.heap.parse_heap(cur_arena)
  File "~/plugins\heap_viewer\ptmalloc.py", line 533, in parse_heap
    status = self.get_chunk(chunk_addr + real_size).prev_inuse
  File "~/plugins\heap_viewer\ptmalloc.py", line 466, in get_chunk
    return get_struct(address, self.malloc_chunk_s)
  File "~/plugins\heap_viewer\misc.py", line 25, in get_struct
    assert idaapi.is_loaded(address) == True, "Can't access memory at 0x%x" % address
AssertionError: Can't access memory at 0x939a000
```
![image](https://user-images.githubusercontent.com/20139227/174786086-5ae95783-a13a-4711-ac8a-723aadafd8c9.png)

## heap-data:
![image](https://user-images.githubusercontent.com/20139227/174786237-642a08d5-8124-4383-bc67-cdc05a65bdd3.png)

**Comment by serfend** [comment]
i solved it by directly use ida-static-libc-version when version-getter fail

**Comment by serfend** [comment]
see #21
