### ISSUE TITLE
Is not friendly for windows ida user?

### ISSUE THREAD

**Issue by asanzjx** [danigargu/heap-viewer#8]
emm,,,,I configure and install like the README.md

yeah ,something is ok,  IDA reminder me "Please wait",so ,I wait,wait,wait....

And I that the IDA are taking up more memory,,,finally the IDA crash

is memory leak?

**Comment by danigargu** [comment]
Hi,

The plugin is compatible with IDA (win2,linux,mac) but only for remote linux binaries (glibc malloc)
Are you debugging a remote linux binary? And you wrote the correct configuration for your libc in the config.json file?

What is the version of your libc?

Thanks!

**Comment by asanzjx** [comment]
Hello,
yeah,I was debugging a remote linux binary that time and the configuration file is correct! So,could you tell me some solution about viewing heap info when i want debug a remote linux bianry use ida ,or say i can only use gdb plugin like pwndbg,gef...thank you very much!

ps:your reply is very quick,thanks again.

**Comment by danigargu** [comment]
If possible, could you send me your libc file and paste the contents of the `config.json` file? I would like to fix the bug (if there is one...)

Thx!

**Comment by asanzjx** [comment]
Hi,
I got some error info about heapview:

Note: FormToPyQtWidget: importing 'sip' module into <module '__main__' from ''>
Note: FormToPyQtWidget: importing 'QtWidgets' module into <module '__main__' from ''>
Traceback (most recent call last):
  File "...\IDA\plugins\heap_viewer\plugin_gui.py", line 192, in cb_arenas_changed
    self.reload_gui_info(True)
  File "...\IDA\plugins\heap_viewer\plugin_gui.py", line 134, in reload_gui_info
    self.arena_widget.populate_table()
  File "...\IDA\plugins\heap_viewer\ui_widgets.py", line 494, in populate_table
    parsed_heap = self.heap.parse_heap(cur_arena)
  File "...\IDA\plugins\heap_viewer\ptmalloc.py", line 539, in parse_heap
    tcache_chunks = self.get_all_tcache_chunks(address)
  File "...\IDA\plugins\heap_viewer\ptmalloc.py", line 485, in get_all_tcache_chunks
    for size, entry in tcache.iteritems():
AttributeError: 'NoneType' object has no attribute 'iteritems'
IDAPython: Error while calling Python callback <OnCreate>:
Traceback (most recent call last):
  File "...\IDA\plugins\heap_viewer\plugin_gui.py", line 49, in OnCreate
    self.populate_gui()
  File "...\IDA\plugins\heap_viewer\plugin_gui.py", line 118, in populate_gui
    self.reload_gui_info()
  File "...\IDA\plugins\heap_viewer\plugin_gui.py", line 134, in reload_gui_info
    self.arena_widget.populate_table()
  File "...\IDA\plugins\heap_viewer\ui_widgets.py", line 494, in populate_table
    parsed_heap = self.heap.parse_heap(cur_arena)
  File "...\IDA\plugins\heap_viewer\ptmalloc.py", line 539, in parse_heap
    tcache_chunks = self.get_all_tcache_chunks(address)
  File "...\IDA\plugins\heap_viewer\ptmalloc.py", line 485, in get_all_tcache_chunks
    for size, entry in tcache.iteritems():
AttributeError: 'NoneType' object has no attribute 'iteritems'

**Comment by danigargu** [comment]
I'll try to fix that, thanks!
Again, can u send me your libc file?

**Comment by danigargu** [comment]
Any comment? Could you solve the problem?
